- package.json
- src/atoms/Input.scss
- src/atoms/Input.tsx
- src/atoms/Select.scss
- src/atoms/Select.tsx
- src/stories/Select.stories.ts
Co-authored-by: Salva <saruba@gmail.com>
> [BOD-121] Delete required & upgrade package version

- .storybook/preview.ts
- package.json
- src/stories/Changelog.stories.mdx
> [BOD-137] Update project version, changelog & docs order

- package.json
- src/atoms/CardsTableList.scss
- src/stories/Changelog.stories.mdx
> [BOD-140] Fix cell padding

- package.json
- src/atoms/CardsTableList.scss
- src/atoms/CardsTableList.tsx
- src/atoms/CardsTableListHeader.tsx
- src/atoms/CardsTableListRow.tsx
- src/stories/CardsTableList.stories.ts
- src/stories/Changelog.stories.mdx
- src/stories/Icons.stories.mdx
- src/stories/ProgrammersStartingGuide.stories.mdx
- src/stories/Welcome.stories.mdx
- src/stories/Workflow.stories.mdx
- src/utils/sort.ts
> [BOD-135] Add sorting to CardsTableList

- .github/workflows/publish-package-to-npmjs.yml
> [BOD-138] Action to publish on npm

- package.json
- src/atoms/Multiselect.scss
- src/atoms/Multiselect.tsx
- src/atoms/Select.scss
- src/atoms/Select.tsx
- src/settings/_depth.scss
- src/stories/Changelog.stories.mdx
- src/stories/Multiselect.stories.ts
- src/stories/Select.stories.ts
> [BOD-177] Select & Multiselect new features

- .github/workflows/run-linters.yml
- package-lock.json
- package.json
- src/atoms/Select.tsx
- src/stories/Changelog.stories.mdx
> [BOD-233] Fix select type

- package-lock.json
- package.json
- src/atoms/Badge.scss
- src/atoms/Badge.tsx
- src/atoms/Button.scss
- src/atoms/IconButton.scss
- src/stories/Badge.stories.ts
- src/stories/Changelog.stories.mdx
- tests/Badge.spec.tsx
> [BOD-234] Create Batch component

- package.json
- src/atoms/Alert.scss
- src/atoms/Alert.tsx
- src/stories/Alert.stories.ts
- src/stories/Changelog.stories.mdx
- tests/Alert.spec.tsx
> [BOD-242] Create Alert component

- package-lock.json
- package.json
- src/atoms/Alert.scss
- src/atoms/Modal.scss
- src/atoms/Modal.tsx
- src/settings/_depth.scss
- src/stories/Changelog.stories.mdx
- src/stories/Modal.stories.js
- tests/Modal.spec.tsx
> [BOD-244] Add position fixed to Modal component

- package.json
- src/atoms/Alert.scss
- src/settings/_depth.scss
- src/stories/Changelog.stories.mdx
> [BOD-256] Fix alert width

- package.json
- src/atoms/Alert.scss
- src/atoms/CardsTable.scss
- src/atoms/CardsTableCell.tsx
- src/settings/typography/_content.scss
- src/stories/CardsTable.stories.js
- src/stories/CardsTableList.stories.ts
- src/stories/Changelog.stories.mdx
- tests/CardsTable.spec.tsx
> [BOD-260] Make Cards Table components responsive

- .storybook/main.ts
- package.json
- src/atoms/Alert.tsx
- src/atoms/Badge.tsx
- src/atoms/Button.tsx
- src/atoms/CardsTable.tsx
- src/atoms/CardsTableCell.tsx
- src/atoms/CardsTableHeader.tsx
- src/atoms/Checkbox.tsx
- src/atoms/EmptyState.tsx
- src/atoms/Icon.tsx
- src/atoms/IconButton.tsx
- src/atoms/Input.tsx
- src/atoms/Modal.tsx
- src/atoms/Multiselect.tsx
- src/atoms/Select.tsx
- src/atoms/TextArea.tsx
- src/stories/Changelog.stories.mdx
- src/stories/Input.stories.ts
- src/stories/TextArea.stories.ts
- src/utils/buildHelpText.ts
- src/utils/classNames.ts
- tests/utils/classNames.spec.tsx
> [BOD-265] Add textarea

- .storybook/main.ts
- package.json
- src/atoms/Alert.tsx
- src/atoms/Badge.tsx
- src/atoms/Button.tsx
- src/atoms/CardsTable.tsx
- src/atoms/CardsTableCell.tsx
- src/atoms/CardsTableHeader.tsx
- src/atoms/Checkbox.tsx
- src/atoms/EmptyState.tsx
- src/atoms/Icon.tsx
- src/atoms/IconButton.tsx
- src/atoms/Input.tsx
- src/atoms/Modal.tsx
- src/atoms/Multiselect.tsx
- src/atoms/Select.tsx
- src/atoms/TextArea.tsx
- src/stories/Changelog.stories.mdx
- src/stories/TextArea.stories.ts
- tests/utils/classNames.spec.tx
> [BOD-270] Fix optional ids and textarea export in the design system

- package.json
- src/atoms/CardsTable.scss
- src/atoms/CardsTableCell.tsx
- src/atoms/CardsTableHeader.tsx
- src/stories/CardsTable.stories.js
> [BOD-275] Card list actions

- package-lock.json
- package.json
- src/atoms/Button/FloatingButton.scss
- src/atoms/Button/FloatingButton.tsx
- src/stories/Changelog.stories.mdx
- src/stories/FloatingButton.stories.ts
> [BOD-352] Update floating button

- package.json
- src/atoms/Collapsible.scss
- src/atoms/Collapsible.tsx
- src/icons/arrow-back.svg
- src/icons/index.tsx
- src/stories/Changelog.stories.mdx
- src/stories/Collapsible.stories.js
- tests/Collapsible.spec.tsx
> [BOD-353] Add collapsible component

- package.json
- src/atoms/Button/Button.scss
- src/atoms/Button/Button.tsx
- src/atoms/Button/IconButton.scss
- src/atoms/Button/IconButton.tsx
- src/atoms/Button/index.ts
- src/atoms/EmptyState.scss
- src/atoms/Pagination/Ellipsis.tsx
- src/atoms/Pagination/Pagination.scss
- src/atoms/Pagination/Pagination.tsx
- src/atoms/Pagination/PaginationArrow.tsx
- src/atoms/Pagination/PaginationNumber.tsx
- src/atoms/Pagination/index.ts
- src/settings/_layers.scss
- src/stories/Changelog.mdx
- src/stories/Pagination.stories.js
- tests/Pagination.spec.tsx
> [BOD-355] Add pagination component

- package.json
- src/atoms/Button/Button.scss
- src/generic/_reset.scss
- src/settings/typography/_content.scss
- src/stories/Changelog.mdx
- src/stories/Typography.stories.js
> [BOD-334] Change typography

- package.json
- src/examples/Typography.scss
- src/examples/Typography.tsx
- src/settings/typography/_content.scss
- src/stories/Changelog.mdx
- src/stories/Typography.stories.js
> [BOD-412] Refactor Typography code & create examples page

- package.json
- src/atoms/Card/Card.scss
- src/atoms/Card/Card.tsx
- src/atoms/CardMenu/CardMenu.scss
- src/atoms/Input.scss
- src/stories/Changelog.mdx
> [BOD-362] Update Cards

- package.json
- src/atoms/Button/IconButton.scss
- src/atoms/Card/Card.scss
- src/atoms/CardMenu/CardMenu.scss
- src/atoms/Menu/Menu.scss
- src/atoms/Menu/MenuDropdown.tsx
- src/atoms/Modal.scss
- src/stories/Card.stories.js
- src/stories/CardMenu.stories.js
- src/stories/Changelog.mdx
- src/stories/Modal.stories.js
> [BOD-373] Orders feedback

- package.json
- src/atoms/CardMenu/CardMenu.scss
- src/atoms/CardsTable/CardsTable.scss
- src/atoms/CardsTable/CardsTable.tsx
- src/stories/CardMenu.stories.js
- src/stories/CardsTable.stories.js
- src/stories/Changelog.mdx
> [BOD-426] Changes for logo mobile

- package.json
- src/atoms/Collapsible.scss
- src/stories/Changelog.mdx
> [BOD-350] Collapsible

- package-lock.json
- package.json
- src/atoms/Alert.scss
- src/atoms/Input.scss
- src/atoms/Input.tsx
- src/atoms/QuantitySelector.scss
- src/atoms/QuantitySelector.tsx
- src/atoms/Select.scss
- src/atoms/TextArea.tsx
- src/stories/Changelog.mdx
- src/stories/Collapsible.stories.js
- src/stories/Input.stories.ts
- src/stories/TextArea.stories.ts
> [BOD-394] Add input with suffix

- package-lock.json
- package.json
- src/atoms/Button/IconButton.scss
- src/atoms/Button/IconButton.tsx
- src/stories/Changelog.mdx
- src/stories/IconButton.stories.ts
> [BOD-422] Add IconButton White variant

- package.json
- src/atoms/Alert.scss
- src/atoms/CardsTable/CardsTable.scss
- src/atoms/DetailItem.scss
- src/atoms/DetailItem.tsx
- src/atoms/Modal.scss
- src/atoms/Modal.tsx
- src/stories/CardsTable.stories.js
- src/stories/Changelog.mdx
- src/stories/Modal.stories.js
> [BOD-407] Add Details modal & components fixes

- package.json
- src/atoms/Collapsible.scss
- src/atoms/Collapsible.tsx
- src/atoms/Modal.scss
- src/atoms/Modal.tsx
- src/stories/Changelog.mdx
- src/stories/Collapsible.stories.js
- src/stories/Modal.stories.js
> [BOD-482] Improve details modal

- package-lock.json
- package.json
- src/atoms/Input.tsx
- src/stories/Changelog.mdx
- tests/Button.spec.tsx
- tests/Checkbox.spec.tsx
- tests/Collapsible.spec.tsx
- tests/EmptyState.spec.tsx
- tests/FloatingButton.spec.tsx
- tests/Icon.spec.tsx
- tests/IconButton.spec.tsx
- tests/Input.spec.tsx
- tests/Multiselect.spec.tsx
- tests/Select.spec.tsx
- tests/TextArea.spec.tsx
- tests/utils/classNames.spec.tsx
> [BOD-503] Add test coverage

- package.json
- src/atoms/Multiselect.scss
- src/atoms/Multiselect.tsx
- src/stories/Changelog.mdx
> [BOD-491] onChange and max height Multiselect

- package.json
- src/stories/Changelog.mdx
> [BOD-491] Update version number

- package-lock.json
- package.json
- src/atoms/Input.scss
- src/stories/Changelog.mdx
> [BOD-432] Fix import

- package-lock.json
- package.json
- src/atoms/Collapsible.tsx
- src/atoms/DetailItem.tsx
- src/stories/Changelog.mdx
> [BOD-525] Add title to collapsible

- package.json
- src/atoms/Collapsible.scss
- src/stories/Changelog.mdx
> [BOD-579] Fix Collapsible header padding bottom

- package.json
- src/atoms/CheckableTag/CheckableTag.tsx
- src/stories/Changelog.mdx
> [BOD-575] Update CheckableTag

- package.json
- src/atoms/Checkbox.scss
- src/atoms/Checkbox.tsx
- src/stories/Changelog.mdx
- tests/Checkbox.spec.tsx
> [BOD-575] Update checkbox

- .github/workflows/publish-package-to-npmjs.yml
- package.json
> [BOD-627] fix publish

- package.json
- src/atoms/Alert/Alert.scss
- src/atoms/Alert/Alert.tsx
- src/atoms/Alert/AlertContainer.scss
- src/atoms/Alert/AlertContainer.tsx
- src/atoms/Alert/index.ts
- src/settings/_depth.scss
- src/stories/Alert.stories.ts
- src/stories/AlertContainer.stories.js
- src/stories/Changelog.mdx
- tests/Alert.spec.tsx
- tsconfig.json
> [BOD-630] AlertContainer and update depth

- package.json
- src/atoms/Select.tsx
> [BOD-647] Fix import

- package.json
- src/atoms/Alert/Alert.scss
- src/stories/Changelog.mdx
⚠️⚠️⚠️ MERGE FIRST DESIGN SYSTEM BRANCH FROM BOD-680
> [BOD-690] Update pointer events to auto on Alert

- package.json
- src/atoms/Select.tsx
- src/stories/Changelog.mdx
> [BOD-693] Update DS with searchable as optional property

- package-lock.json
- package.json
> [BOD-639] Update dependencies

- package.json
- src/atoms/Multiselect.tsx
- src/atoms/Select.tsx
- src/stories/Changelog.mdx
> [BOD-717] Fix state of search select

- package.json
- src/atoms/Badge.tsx
- src/atoms/QuantitySelector.tsx
- src/stories/Changelog.mdx
> [BOD-674] Fix Quantity Selector

- package.json
- src/atoms/Button/Button.tsx
- src/stories/Changelog.mdx
> [BOD-744] Fix icon size for button component

- package.json
- src/atoms/Collapsible.scss
- src/stories/Changelog.mdx
> [BOD-758] Fix Collapsible non-desired default icon on Safari

- package-lock.json
- package.json
- src/atoms/Checkbox.scss
- src/stories/Changelog.mdx
- src/stories/Checkbox.stories.ts
> [BOD-703] Fix hover style when Checkbox component is disabled

- package-lock.json
- package.json
- src/atoms/Modal.scss
- src/atoms/Modal.tsx
- src/stories/Changelog.mdx
- src/stories/Modal.stories.js
> [BOD-703] Make scrolling in Modal component optional

- package.json
- src/atoms/Modal.scss
- src/stories/Changelog.mdx
> [BOD-703] Fix detail modal component height

- .github/workflows/publish-package-to-npmjs.yml
- package-lock.json
- src/atoms/DatePicker.tsx
- src/stories/Changelog.mdx
- src/stories/DatePicker.stories.ts
> [BOD-725] Update version & add missing refactor

- package.json
- src/atoms/CardsTable/CardsTable.scss
- src/atoms/Icon.scss
- src/stories/CardsTable.stories.js
- src/stories/Changelog.mdx
> [BOD-761] Align card table rows top

- package.json
- src/atoms/Modal/Modal.tsx
- src/stories/Changelog.mdx
- src/stories/Modal.stories.js
> [BOD-820] Remove close button property

- package.json
- src/atoms/Modal/Modal.scss
- src/atoms/Modal/ModalDialog.tsx
- src/stories/Changelog.mdx
- src/stories/Modal.stories.js
> [BOD-820] Modal fix scroll

- package.json
- src/atoms/Button/Button.tsx
- src/atoms/Button/FloatingButton.tsx
- src/atoms/Button/IconButton.tsx
- src/atoms/Select.tsx
- src/stories/Button.stories.ts
- src/stories/Changelog.mdx
- src/stories/FloatingButton.stories.ts
- src/stories/IconButton.stories.ts
> [BOD-827] Add loading to icon and floating buttons

- package.json
- src/atoms/Switch.scss
- src/atoms/Switch.tsx
- src/stories/Changelog.mdx
- src/stories/Switch.stories.ts
- tests/Switch.spec.tsx
> [BOD-837] Add Switch component

- package.json
- src/atoms/Multiselect.tsx
- src/atoms/QuantitySelector.tsx
- src/atoms/Select.tsx
- src/stories/Changelog.mdx
- src/stories/QuantitySelector.stories.ts
> [BOD-867] Autofocus on search input in the Select and MultiSelect components

- package.json
- src/atoms/Button/BaseButton.tsx
- src/atoms/Card/Card.tsx
- src/atoms/CardMenu/CardMenuOption.tsx
- src/atoms/Menu/MenuLink.tsx
- src/atoms/Pagination/PaginationArrow.tsx
- src/atoms/Pagination/PaginationNumber.tsx
- src/atoms/Popover/PopoverMenuOption.tsx
- src/generic/_helpers.scss
- src/stories/Changelog.mdx
> [BOD-872] No prefetch links

- package.json
- src/atoms/Card/Card.scss
- src/stories/Card.stories.js
- src/stories/Changelog.mdx
> [BOD-870] Fix Footer position and width on Card 

- package.json
- src/atoms/CardsTable/CardsTable.scss
- src/stories/Changelog.mdx
> [BOD-871] Add margin-top to all cells containing Badge on CardsTable

- package.json
- src/atoms/Card/Card.scss
- src/atoms/Pagination/Pagination.scss
- src/stories/Card.stories.js
- src/stories/Changelog.mdx
> [BOD-874] Add Card hover & fix Pagination hover

- package.json
- src/atoms/DatePicker/DateRangePicker.tsx
- src/atoms/DatePicker/DateSinglePicker.tsx
- src/atoms/DatePicker/translations.ts
- src/stories/Changelog.mdx
> [BOD-894] Change footer text

- package.json
- src/atoms/DatePicker/DateRangePicker.tsx
- src/stories/Changelog.mdx
> [BOD-894] Change footer text date picker

- package.json
- src/atoms/CardsTable/CardsTable.scss
- src/atoms/CardsTable/CardsTableBody.tsx
- src/atoms/CardsTable/CardsTableCell.tsx
- src/atoms/CardsTable/CardsTableHead.tsx
- src/atoms/CardsTable/CardsTableHeader.tsx
- src/atoms/CardsTable/CardsTableRow.tsx
- src/atoms/DatePicker/DatePicker.scss
- src/atoms/DatePicker/DateRangePicker.tsx
- src/atoms/DatePicker/DateSinglePicker.tsx
- src/atoms/Input.tsx
- src/hooks/useOpen.ts
- src/stories/Changelog.mdx
- src/stories/DateRangePicker.stories.ts
- src/stories/DateSinglePicker.stories.ts
> [BOD-865] Refactor card table and improve date picker funcionality

- package.json
- src/atoms/DatePicker/DatePicker.scss
- src/atoms/DatePicker/DateRangePicker.tsx
- src/atoms/DatePicker/DateSinglePicker.tsx
- src/stories/Changelog.mdx
- src/stories/DateRangePicker.stories.ts
- src/stories/DateSinglePicker.stories.ts
> [BOD-941] Show errors in Datepickers

- package.json
- src/stories/Changelog.mdx
> [BOD-1007] Update DS version because of not using beta

- package.json
- src/atoms/Input.scss
- src/stories/Changelog.mdx
> [BOD-944] Input text color

- package.json
- src/atoms/Select/Select.tsx
- src/atoms/Select/SelectTrigger.tsx
- src/stories/Changelog.mdx
- tests/Multiselect.spec.tsx
- tests/Select.spec.tsx
> [BOD-1053] Fix submit form when click in deselect button

- package.json
- src/atoms/TabMenu/TabLink.tsx
- src/atoms/TabMenu/TabMenu.scss
- src/atoms/TabMenu/TabMenu.tsx
- src/atoms/TabMenu/index.ts
- src/stories/Changelog.mdx
- src/stories/TabMenu.stories.js
- tests/TabMenu.spec.tsx
> [BOD-1049] Create TabMenu component

- package-lock.json
- package.json
- src/atoms/RadioGroup/RadioGroup.tsx
- src/stories/Changelog.mdx
- src/stories/RadioGroup.stories.ts
> [BOD-1056] Add onChange prop to RadioGroup component

- package.json
- src/atoms/Divider.scss
- src/atoms/Divider.tsx
- src/stories/Changelog.mdx
- src/stories/Collapsible.stories.js
- src/stories/Divider.stories.ts
- src/stories/Modal.stories.js
> [BOD-1059] Add hasAction & onClick property to Divider component

- package.json
- src/atoms/TabMenu/TabMenu.scss
- src/stories/Changelog.mdx
> [BOD-1108] Fix TabMenu styles

- package.json
- src/atoms/TabMenu/TabMenu.scss
- src/stories/Changelog.mdx
> [BOD-1119] Fix TabMenu active link border

- package.json
- src/atoms/TabMenu/TabMenu.scss
- src/stories/Changelog.mdx
> [BOD-1121] Fix TabMenu hover link border

- package-lock.json
- package.json
- src/atoms/Button/Button.scss
- src/atoms/Button/Button.tsx
- src/atoms/ButtonGroup/ButtonGroup.scss
- src/atoms/ButtonGroup/ButtonGroup.tsx
- src/atoms/ButtonGroup/index.ts
- src/atoms/Popover/Popover.scss
- src/atoms/Popover/Popover.tsx
- src/atoms/Popover/PopoverMenu.tsx
- src/atoms/Popover/PopoverMenuOption.tsx
- src/icons/index.tsx
- src/icons/more.svg
- src/stories/Button.stories.ts
- src/stories/ButtonGroup.stories.tsx
- src/stories/Changelog.mdx
- src/stories/Popover.stories.tsx
- tests/Popover.spec.tsx
> [BOD-1115] Add ButtonGroup component

- package.json
- src/atoms/Checkbox.tsx
- src/stories/Changelog.mdx
> [BOD-1165] Remove non-desired accessibilityLabel use on Checkbox

- package-lock.json
- package.json
- src/atoms/Drawer.scss
- src/atoms/Drawer.tsx
- src/stories/Changelog.mdx
- src/stories/Drawer.stories.tsx
> [BOD-1241] Improve Filters Drawer UX

- package.json
- src/atoms/Button/BaseButton.tsx
- src/atoms/Select/InfiniteSelect.tsx
- src/atoms/Select/MultiSelect.tsx
- src/atoms/Select/Select.tsx
- src/stories/Changelog.mdx
> [BOD-1278] Fix base button props and select components
